### ISSUE TITLE
Pex dependency contradiction

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3675]
### Observed behavior

We have put an upper limit on the `pex` dependency in `requirements/build.txt`. However, this results in a version conflict:

```
pex 1.2.16 has requirement wheel<0.30.0,>=0.26.0, but you'll have wheel 0.31.1 which is incompatible.
```

It doesn't look nice because Pex would probably have a reason for this?

It seems, though, that `wheel` without a version results in `0.31.1` being downloaded AFTER installing `pex`.

The simple solution would be to remove `wheel` from `requirements/build.txt` and rely on the one shipped.

### Expected behavior

No version conflicts + use newer Pex? 1.4.0 is the latest (released today).

### Errors and logs

```
piptree requirements/build.txt 
Sphinx 1.7.4
└── sphinxcontrib-websupport
└── babel
    └── pytz
└── imagesize
└── setuptools
└── packaging
    └── pyparsing
    └── six
└── Pygments
└── requests
    └── idna
    └── urllib3
    └── certifi
    └── chardet
└── six
└── docutils
└── typing
└── alabaster
└── Jinja2
    └── MarkupSafe
└── snowballstemmer
sphinx-autobuild 0.7.1
└── port-for
└── tornado
    └── futures
    └── singledispatch
     └── six
    └── backports-abc
└── pathtools
└── livereload
    └── six
    └── tornado
     └── futures
     └── singledispatch
      └── six
     └── backports-abc
└── PyYAML
└── argh
└── watchdog
    └── argh
    └── pathtools
    └── PyYAML
sphinx-intl 0.9.11
└── six
└── sphinx
    └── sphinxcontrib-websupport
    └── babel
     └── pytz
    └── imagesize
    └── setuptools
    └── packaging
     └── pyparsing
     └── six
    └── Pygments
    └── requests
     └── idna
     └── urllib3
     └── certifi
     └── chardet
    └── six
    └── docutils
    └── typing
    └── alabaster
    └── Jinja2
     └── MarkupSafe
    └── snowballstemmer
└── babel
    └── pytz
└── click
└── setuptools
sphinx-rtd-theme 0.3.1
wheel 0.31.1
```

**Comment by rtibbles** [comment]
@aronasorman was there a reason for limiting the pex version, or can we upgrade?

**Comment by aronasorman** [comment]
I just like pinned versions :D feel free to upgrade.

**Comment by aronasorman** [comment]
I just think that we shouldn't leave this unpinned, as I remember pex had some breaking changes before, regarding their options. I think I've fixed that in a previous upgrade, but then that's why I pinned it.

**Comment by benjaoming** [comment]
It's not actually pinned, it was a pre-cautious `<1.3` :)

But yes, I remember the same as @aronasorman -- we had problems IIRC with a namespaced dependencies in Pex which broke our way of bundling dependencies. But as long as this issue isn't fixed, we're good: https://github.com/cherrypy/cherrypy/issues/1673

I think we can bump it to `<1.5` and have PyUp alert us further minor version updates, while accepting the patch updates automatically?

**Comment by benjaoming** [comment]
Oh yeah, btw there is an actual assertion that no packages are namespaced in our `make test-namespaced-packages` target which is run through `make staticdeps`, so our whole build chain fails if it happens again.
