### ISSUE TITLE
Check that Kolibri does not fail to start when deleting the home folder contents

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6519]
### Observed behavior
During the testing of Kolibri mac installer I found this issue when deleting the home folder contents will cause an error and kolibri can't start the server. here's the [issue](https://github.com/learningequality/kolibri-installer-mac/issues/51#issuecomment-581786009) I reported on mac installer repo

@kollivier has a comment about this issue here https://github.com/learningequality/kolibri-installer-mac/issues/51#issuecomment-582021971:

> It turns out that the issue is that when you delete the contents of `~/.kolibri` from Finder, it leaves the hidden `.data_version` file, and Kolibri uses that file to determine when it needs to run migrations

### Expected behavior

If Kolibri finds a `.data_version` file but no database, perhaps it should clear the file?

### User-facing consequences

In some situations, user might think they have reset Kolibri but get into a stuck state. I believe if they delete the entire `.kolibri` folder this would not happen.

### Errors and logs
 
[kolibri.txt](https://github.com/learningequality/kolibri/files/4158063/kolibri.txt)
[kolibri-app.txt](https://github.com/learningequality/kolibri/files/4158065/kolibri-app.txt)

### Steps to reproduce

Delete all non-hidden files from `~/.kolibri`

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13
 * Operating system: macOS 10.14.6
 * Browser

**Comment by oldmanscreaming** [comment]
Would it be alright to add the file check to the initialize function in the kolibri.utils.cli module? 
 
```python
def initialize(skip_update=False): 
```
does the database migration occur in the _setup_django() function as well?

```python
def _setup_django():
```

what should happen is that once kolibri finds the .data_version file but no database, it should run the database migration?

**Comment by jonboiser** [comment]
> what should happen is that once kolibri finds the .data_version file but no database, it should run the database migration?

I think that sounds like a good strategy. So here's the user story. This should work the same whether using the Mac App DMG file, or the Kolibri python executable that just runs a Kolibri server.

```
Given I have started Kolibri once on my Mac (or UNIX-based) computer
	And my kolibri home folder (usually ~/.kolibri) contains sqlite database files
When I delete all the files except ~/.kolibri/.data_version
	And restart kolibri with "kolibri start"
Then the database migrations are run and a new database is created for me
	And kolibri starts again on the Setup Wizard
```

**Comment by rtibbles** [comment]
This is mostly a matter of checking that the functionality implemented here is actually working: https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/utils/cli.py#L397
As this should already be checking whether the database is migrated, and then attempting to run the migrations. This will be the case regardless of whether `.data_version` exists or not.

Also, as this code was last modified around the same time that this issue was reported, it is possible that this issue is now fixed, so confirming that it is still extant would be a good first step.

**Comment by radinamatic** [comment]
@jonboiser Does this need a proper Gherkin scenario, or the _user story_ above is just a suggestion for a possible fix to implement?

cc @pcenov

**Comment by rtibbles** [comment]
Flagging that I just ran Kolibri locally with this exact setup:
Empty Kolibri Home dir, except for `.data_version` file

And migrations did indeed run. I think this issue is stale, would be good to add a CLI test to assert this behaviour, but no fix is needed here.

**Comment by jonboiser** [comment]
> @jonboiser Does this need a proper Gherkin scenario, or the _user story_ above is just a suggestion for a possible fix to implement?

It's a user story to confirm that this bug still exists or not (Richard seems to have gone through the story himself and found the bug doesn't exist anymore). 

We can just add it to the list of Gherkins, esp. with the proper variations for Windows.

**Comment by nucleogenesis** [comment]
@rtibbles This issue or something that is very much like it (it's different, issue made here #7952) - fails the first run of `yarn devserver` if the `KOLIBRI_HOME` I am targeting doesn't exist. I thought this was tracked but I'm not sure if it's this issue or another.

The report for this was specific to the Mac installer - when you tested this did you try it with the Mac OS installer to be sure that the bug is resolved in the original context? Even if this bug exists, it's such an edge case with very little impact when hit.

> would be good to add a CLI test to assert this behaviour,

If this is confirmed not to exist on Mac any longer, we'll update this issue to be about adding a test to assert that behaviour.

**Comment by rtibbles** [comment]
Have just posted in #7952 - I was unable to replicate that issue either.
